#!/bin/sh

if grep '^ *[0-9].* eps' "$@"; then
echo "FAILED!"
exit 2
fi
printf "PASSED: "
cat "$@" | grep -c 'All tests were passed'
printf "WEAK: "
cat "$@" | grep -c 'The following tests gave p-values outside'
exit 0
